---
abstract: 'Command-line tool to help build and test bleadperl'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-grindperl
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  App::grindperl:
    file: lib/App/grindperl.pm
    version: 0.001
requires:
  Carp: 0
  File::Copy: 0
  File::HomeDir: 0.98
  Getopt::Lucid: 0
  Path::Class: 0
  autodie: 0
  namespace::autoclean: 0
  perl: v5.10.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-grindperl
  homepage: http://github.com/dagolden/app-grindperl
  repository: http://github.com/dagolden/app-grindperl
version: 0.001
